# cfgs/ddpm/ddpm_model.yaml

class_path: models.ddpmModel2.DDPMLightning
init_args:
  # This should match the number of channels/features provided by your dataloader.
  # The error log indicates this is 40.
  n_channels: 40
  flatten_temporal_dimension: True # Set to True, logic will be in the model
  pos_class_weight: 236.0          # Positive class weight
  loss_function: "L2"              # Dummy for compatibility

  # --- DDPM specific parameters ---
  unet_params:
    image_size: 64
    in_target_channels: 1
    # This MUST match the channels from the dataloader.
    in_condition_channels: 40
    model_channels: 64
    out_channels: 1
    num_res_blocks: 2
    channel_mult: [1, 2, 4, 8]
    time_emb_dim_mult: 4
    groups: 8

  diffusion_params:
    image_size: 64
    timesteps: 200
    beta_schedule_type: "linear"
    target_channels: 1

  optimizer_cfg:
    class_path: torch.optim.AdamW
    init_args:
      lr: 0.0001
      weight_decay: 0.01

  metrics_cfg: {}